image_encoder:
  vit_Large:
    patch_size: 16
    hidden_size: 1024
    num_layers: 24
    n_head: 16
    image_size: 224
    dropout_pro: 0.1
    dim_feedforward: 2048
    image_embedding_size: 4096
  
text_encoder:
  distilbert:
    name: distilbert-base-uncased
    text_embedding_size: 1024

dropout_prob: 0.2
shared_dim: 1024